spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fintech_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8082