spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fintech_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

jwt:
  secret: 4c7fd1b8cfa88f53d0e8d1d8d97fd09a7b47c7b8e65dbf5d11eab2d47bfc8890
  access-token-expiration: 900000
  refresh-token-expiration: 604800000